/**
 * File: backend/server.js
 * ─────────────────────────────────────────────────────────────
 * Folio — GitHub Pages Deployment Backend
 *
 * POST /deploy
 *   Accepts portfolio data, writes to GitHub repo `portfolio-hub`,
 *   enables Pages, and returns the live GitHub Pages URL.
 *
 * Required env vars (see .env.example):
 *   GITHUB_TOKEN    — Personal access token (scopes: repo, pages)
 *   GITHUB_USERNAME — Your GitHub username (e.g. "octocat")
 *
 * Run:
 *   npm install
 *   cp .env.example .env   # fill in your values
 *   node server.js
 * ─────────────────────────────────────────────────────────────
 */

'use strict';

const express    = require('express');
const cors       = require('cors');
const dotenv     = require('dotenv');
const { Octokit } = require('@octokit/rest');

// ── Load env ─────────────────────────────────────────────────
dotenv.config();

const {
  GITHUB_TOKEN,
  GITHUB_USERNAME,
  PORT = 3001,
} = process.env;

if (!GITHUB_TOKEN || !GITHUB_USERNAME) {
  console.error(
    '❌  Missing env vars. Copy .env.example → .env and fill in GITHUB_TOKEN and GITHUB_USERNAME.'
  );
  process.exit(1);
}

// ── Express setup ─────────────────────────────────────────────
const app = express();

// Allow requests from the Folio HTML frontend (any origin in dev)
app.use(cors({ origin: '*' }));
app.use(express.json({ limit: '10mb' }));

// ── Octokit ───────────────────────────────────────────────────
const octokit = new Octokit({ auth: GITHUB_TOKEN });

// Shared constants
const REPO_NAME    = 'portfolio-hub';
const PAGES_BRANCH = 'main';

// ─────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────

/**
 * Ensure the `portfolio-hub` repository exists.
 * Creates it as a public repo if it doesn't.
 * Returns the repo data object.
 */
async function ensureRepo() {
  try {
    const { data } = await octokit.repos.get({
      owner: GITHUB_USERNAME,
      repo:  REPO_NAME,
    });
    return data;
  } catch (err) {
    if (err.status !== 404) throw err;

    // Repo doesn't exist — create it
    console.log(`📦  Creating repo: ${GITHUB_USERNAME}/${REPO_NAME}`);
    const { data } = await octokit.repos.createForAuthenticatedUser({
      name:          REPO_NAME,
      description:   'Portfolios generated by Folio — folio.app',
      private:       false,
      auto_init:     true,   // creates an initial commit so Pages can be enabled
      has_issues:    false,
      has_projects:  false,
      has_wiki:      false,
    });
    return data;
  }
}

/**
 * Build a minimal standalone HTML page wrapping the portfolio innerHTML.
 * Includes all the fonts and a reset so it renders correctly without
 * the parent app shell.
 */
function buildStandaloneHTML(slug, name, portfolioHTML, theme, wizard) {
  const paletteAccent = '#d4a853'; // default; the inline styles inside portfolioHTML already carry palette vars

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>${escapeHTML(name)} — Portfolio</title>
<meta name="description" content="Portfolio of ${escapeHTML(name)}, generated with Folio."/>
<meta property="og:title" content="${escapeHTML(name)}'s Portfolio"/>
<meta property="og:type" content="website"/>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600&family=Outfit:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&family=Poppins:wght@300;400;500;600;700&family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=Roboto+Slab:wght@300;400;600;700&family=Pacifico&family=Baloo+2:wght@400;500;600;700&family=Orbitron:wght@400;500;600;700&display=swap" rel="stylesheet"/>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html{scroll-behavior:smooth}
body{font-family:'Outfit',system-ui,sans-serif;overflow-x:hidden;line-height:1.7}
a{color:inherit;text-decoration:none}
img{max-width:100%;display:block}

/* ── Theme variables ── */
:root{
  --dw-primary:${paletteAccent};
  --dw-accent:#8b5cf6;
  --dw-font-display:'Cormorant Garamond',Georgia,serif;
  --dw-font-body:'Outfit',sans-serif;
}

/* ── Developer theme (default) ── */
[data-theme=developer]{--t-bg:#080810;--t-bg2:#0e0e1a;--t-bg3:#15151f;--t-surf:#1c1c2a;--t-b:rgba(255,255,255,.06);--t-b2:rgba(255,255,255,.11);--t-acc:var(--dw-primary,#d4a853);--t-acc2:var(--dw-accent,#8b5cf6);--t-tx:#ddd8cc;--t-mu:#7a7568;--t-di:#3a3830;--t-wh:#fff;--t-fh:var(--dw-font-display);--t-fb:var(--dw-font-body);--t-fm:'JetBrains Mono',monospace}
[data-theme=minimal]{--t-bg:#f6f4ee;--t-bg2:#edeadf;--t-bg3:#e5e2d6;--t-surf:#fff;--t-b:rgba(0,0,0,.07);--t-b2:rgba(0,0,0,.13);--t-acc:var(--dw-primary,#2b4a10);--t-acc2:var(--dw-accent,#6b4f2a);--t-tx:#1a1a14;--t-mu:#5e5a52;--t-di:#b0ad9e;--t-wh:#1a1a14;--t-fh:var(--dw-font-display);--t-fb:var(--dw-font-body);--t-fm:'JetBrains Mono',monospace}
[data-theme=creative]{--t-bg:#0a0620;--t-bg2:#100830;--t-bg3:#160b3e;--t-surf:#1e1050;--t-b:rgba(255,255,255,.07);--t-b2:rgba(255,255,255,.14);--t-acc:var(--dw-primary,#a78bfa);--t-acc2:var(--dw-accent,#f472b6);--t-tx:#ece8ff;--t-mu:#9b94c8;--t-di:#4a4480;--t-wh:#fff;--t-fh:var(--dw-font-display);--t-fb:var(--dw-font-body);--t-fm:'JetBrains Mono',monospace}
[data-theme=designer]{--t-bg:#fdf8f2;--t-bg2:#f7f0e6;--t-bg3:#efe5d6;--t-surf:#fff;--t-b:rgba(0,0,0,.07);--t-b2:rgba(0,0,0,.13);--t-acc:var(--dw-primary,#c0633a);--t-acc2:var(--dw-accent,#e8a87c);--t-tx:#2c1f14;--t-mu:#7a6a5a;--t-di:#c5b8a8;--t-wh:#2c1f14;--t-fh:var(--dw-font-display);--t-fb:var(--dw-font-body);--t-fm:'JetBrains Mono',monospace}

/* ── Core portfolio layout (copied from app CSS) ── */
.pt{background:var(--t-bg);color:var(--t-tx);font-family:var(--t-fb)}
.pt-hero{min-height:92vh;display:flex;align-items:center;background:var(--t-bg);position:relative;overflow:hidden;padding:5rem 2rem 4rem}
.pt-orb{position:absolute;border-radius:50%;filter:blur(85px);opacity:.1;pointer-events:none}
.pt-o1{width:500px;height:500px;background:var(--t-acc);top:-160px;right:-100px}
.pt-o2{width:350px;height:350px;background:var(--t-acc2);bottom:-120px;left:-80px}
[data-theme=minimal] .pt-orb,[data-theme=designer] .pt-orb{opacity:.05}
.pt-hi{position:relative;z-index:1;max-width:1100px;margin:0 auto;width:100%}
.pt-greet{font-family:var(--t-fm);font-size:.72rem;letter-spacing:.2em;text-transform:uppercase;color:var(--t-acc);margin-bottom:1rem}
.pt-name{font-family:var(--t-fh);font-size:clamp(2.8rem,6vw,5.2rem);font-weight:700;line-height:1.04;color:var(--t-wh);margin-bottom:.7rem}
.pt-ttl{font-size:1.15rem;color:var(--t-acc);font-weight:300;margin-bottom:1.4rem}
.pt-bio{color:var(--t-mu);line-height:1.85;max-width:480px;margin-bottom:2rem;font-size:.98rem}
.pt-photo{position:absolute;right:0;top:50%;transform:translateY(-50%);width:240px;height:240px;border-radius:50%;object-fit:cover;border:2px solid var(--t-b2);box-shadow:0 20px 60px rgba(0,0,0,.45)}
.pt-hlinks{display:flex;gap:.7rem;flex-wrap:wrap}
.pt-hl{display:inline-flex;align-items:center;gap:.4em;padding:.52em 1.15em;border-radius:6px;font-size:.85rem;font-weight:500;border:1px solid var(--t-b2);color:var(--t-mu);background:var(--t-surf);transition:all .2s}
.pt-hl:hover{border-color:var(--t-acc);color:var(--t-acc)}
.pt-hl-p{background:var(--t-acc);color:var(--t-bg);border-color:var(--t-acc);font-weight:700}
.pt-sec{padding:5.5rem 2rem;background:var(--t-bg2)}
.pt-sec:nth-child(odd){background:var(--t-bg)}
.pt-con{max-width:1100px;margin:0 auto}
.pt-ey{font-family:var(--t-fm);font-size:.68rem;letter-spacing:.2em;text-transform:uppercase;color:var(--t-acc);margin-bottom:.7rem}
.pt-stitle{font-family:var(--t-fh);font-size:clamp(1.8rem,3vw,2.6rem);font-weight:600;color:var(--t-wh);margin-bottom:2.8rem;line-height:1.15}
.pt-stitle em{font-style:italic;color:var(--t-acc)}
.pt-ag{display:grid;grid-template-columns:1fr 1fr;gap:3.5rem;align-items:center}
.pt-atx{color:var(--t-mu);line-height:1.9;font-size:1rem}
.pt-meta{display:flex;flex-direction:column;gap:.9rem}
.pt-mi{display:flex;align-items:center;gap:1rem}
.pt-mico{font-size:.95rem;color:var(--t-acc)}
.pt-mv small{color:var(--t-di);font-size:.72rem;display:block;font-family:var(--t-fm)}
.pt-mv strong{color:var(--t-tx);font-size:.9rem}
.pt-sg{display:grid;grid-template-columns:repeat(2,1fr);gap:.9rem}
.pt-ski{background:var(--t-surf);border:1px solid var(--t-b);border-radius:10px;padding:1.2rem 1.4rem}
.pt-skh{display:flex;justify-content:space-between;align-items:center;margin-bottom:.65rem}
.pt-skn{font-weight:600;color:var(--t-tx);font-size:.9rem}
.pt-skp{font-family:var(--t-fm);font-size:.72rem;color:var(--t-acc)}
.pt-sbg{height:4px;background:var(--t-b2);border-radius:2px;overflow:hidden}
.pt-sbl{height:100%;background:linear-gradient(to right,var(--t-acc),var(--t-acc2));border-radius:2px}
.pt-pg{display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:1.4rem}
.pt-pc{background:var(--t-surf);border:1px solid var(--t-b);border-radius:14px;overflow:hidden}
.pt-pi{width:100%;height:170px;background:linear-gradient(135deg,var(--t-bg3),var(--t-surf));display:flex;align-items:center;justify-content:center;font-size:2.4rem;color:var(--t-di)}
.pt-pb{padding:1.4rem}
.pt-pt{font-family:var(--t-fh);font-size:1.1rem;font-weight:600;color:var(--t-wh);margin-bottom:.55rem}
.pt-pd{color:var(--t-mu);font-size:.85rem;line-height:1.7;margin-bottom:.9rem}
.pt-ptgs{display:flex;flex-wrap:wrap;gap:.35rem;margin-bottom:.9rem}
.pt-ptg{padding:.2em .65em;background:rgba(212,168,83,.07);border:1px solid rgba(212,168,83,.14);border-radius:4px;font-size:.72rem;color:var(--t-acc);font-family:var(--t-fm)}
.pt-pls{display:flex;gap:.75rem}
.pt-pl{font-size:.8rem;color:var(--t-mu);display:flex;align-items:center;gap:.3em;transition:color .2s}
.pt-pl:hover{color:var(--t-acc)}
.pt-tl{position:relative;padding-left:1.8rem}
.pt-tl::before{content:'';position:absolute;left:0;top:0;bottom:0;width:1px;background:var(--t-b2)}
.pt-te{position:relative;margin-bottom:2.6rem;padding-left:1.8rem}
.pt-te::before{content:'';position:absolute;left:-2.25rem;top:.35rem;width:13px;height:13px;border-radius:50%;background:var(--t-acc);border:2px solid var(--t-bg2)}
.pt-td{font-family:var(--t-fm);font-size:.72rem;color:var(--t-acc);margin-bottom:.45rem}
.pt-tr{font-family:var(--t-fh);font-size:1.1rem;font-weight:600;color:var(--t-wh);margin-bottom:.2rem}
.pt-tc{color:var(--t-mu);font-size:.88rem;margin-bottom:.6rem}
.pt-tds{color:var(--t-mu);font-size:.87rem;line-height:1.7}
.pt-eg{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:1.1rem}
.pt-ec{background:var(--t-surf);border:1px solid var(--t-b);border-radius:12px;padding:1.4rem}
.pt-eic{font-size:1.4rem;margin-bottom:.65rem}
.pt-edg{font-family:var(--t-fh);font-size:1.02rem;font-weight:600;color:var(--t-wh);margin-bottom:.25rem}
.pt-ein{color:var(--t-mu);font-size:.87rem;margin-bottom:.2rem}
.pt-eyr{font-family:var(--t-fm);font-size:.7rem;color:var(--t-acc)}
.pt-cg{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:.9rem}
.pt-cc{display:flex;align-items:center;gap:.9rem;background:var(--t-surf);border:1px solid var(--t-b);border-radius:11px;padding:1.2rem 1.4rem}
.pt-cico{font-size:1.2rem}
.pt-clb{font-size:.7rem;color:var(--t-di);display:block;font-family:var(--t-fm)}
.pt-cv{color:var(--t-tx);font-size:.87rem}
.pt-foot{padding:2rem;text-align:center;background:var(--t-bg);border-top:1px solid var(--t-b)}
.pt-foot span{font-family:var(--t-fm);font-size:.72rem;color:var(--t-di)}
.pt-foot span b{color:var(--t-acc)}
.pt-industry-badge{display:inline-flex;align-items:center;gap:.35em;padding:.22em .7em;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.12);border-radius:20px;font-family:var(--t-fm);font-size:.65rem;color:var(--t-acc);letter-spacing:.05em;margin-left:.5rem;vertical-align:middle}
/* Scroll reveal — pre-revealed for static page */
.ptr{opacity:1;transform:none}
@media(max-width:768px){.pt-photo{display:none}.pt-ag{grid-template-columns:1fr}.pt-sg{grid-template-columns:1fr}}
</style>
</head>
<body>
<div id="pt-root" data-theme="${escapeHTML(theme)}">
${portfolioHTML}
</div>
</body>
</html>`;
}

/** Minimal HTML entity escaping for attribute values */
function escapeHTML(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Create or update a file in the repo using the GitHub Contents API.
 * If the file already exists, its SHA is required to update it.
 */
async function putFile(path, content, message) {
  // Try to get existing file SHA
  let sha;
  try {
    const { data } = await octokit.repos.getContent({
      owner: GITHUB_USERNAME,
      repo:  REPO_NAME,
      path,
    });
    sha = data.sha;
  } catch (err) {
    if (err.status !== 404) throw err;
    // File doesn't exist yet — sha stays undefined (create mode)
  }

  await octokit.repos.createOrUpdateFileContents({
    owner:   GITHUB_USERNAME,
    repo:    REPO_NAME,
    path,
    message,
    content: Buffer.from(content, 'utf8').toString('base64'),
    ...(sha ? { sha } : {}),
    branch:  PAGES_BRANCH,
  });
}

/**
 * Enable GitHub Pages on the repo (source: main branch, / root).
 * Silently ignores 409 (already enabled) errors.
 */
async function ensurePages() {
  try {
    await octokit.repos.createPagesSite({
      owner:  GITHUB_USERNAME,
      repo:   REPO_NAME,
      source: { branch: PAGES_BRANCH, path: '/' },
    });
    console.log('📄  GitHub Pages enabled');
  } catch (err) {
    // 409 = Pages already configured, 422 = same — both are fine
    if (err.status !== 409 && err.status !== 422) {
      console.warn('⚠️   Pages setup warning:', err.message);
    }
  }
}

// ─────────────────────────────────────────────────────────────
// ROUTES
// ─────────────────────────────────────────────────────────────

/**
 * GET /health
 * Simple liveness check.
 */
app.get('/health', (_req, res) => {
  res.json({ status: 'ok', user: GITHUB_USERNAME });
});

/**
 * POST /deploy
 *
 * Body (JSON):
 * {
 *   slug:   string   — URL-safe identifier (e.g. "alex-morgan")
 *   name:   string   — Display name
 *   html:   string   — The rendered portfolio innerHTML from the frontend
 *   theme:  string   — Active theme key ("developer"|"minimal"|"creative"|"designer")
 *   wizard: {        — Wizard selections (for metadata)
 *     industry: string | null,
 *     palette:  string | null,
 *     font:     string | null,
 *   }
 * }
 *
 * Response:
 * { url: "https://{username}.github.io/portfolio-hub/portfolios/{slug}" }
 */
app.post('/deploy', async (req, res) => {
  const { slug, name, html, theme = 'developer', wizard = {} } = req.body;

  // ── Validate ──────────────────────────────────────────────
  if (!slug || typeof slug !== 'string' || !/^[a-z0-9-]+$/.test(slug)) {
    return res.status(400).json({ error: 'Invalid or missing slug. Must be lowercase letters, numbers, and hyphens only.' });
  }
  if (!html || typeof html !== 'string') {
    return res.status(400).json({ error: 'Missing html payload.' });
  }
  if (html.length > 8_000_000) { // 8MB safety cap
    return res.status(413).json({ error: 'HTML payload too large (max 8MB).' });
  }

  console.log(`🚀  Deploying portfolio: ${slug} (theme: ${theme})`);

  try {
    // 1. Ensure the repo exists
    await ensureRepo();

    // 2. Build the standalone HTML page
    const pageHTML = buildStandaloneHTML(slug, name, html, theme, wizard);

    // 3. Write the file to portfolios/{slug}/index.html
    const filePath = `portfolios/${slug}/index.html`;
    await putFile(
      filePath,
      pageHTML,
      `🚀 Deploy portfolio: ${name} (${slug})`
    );
    console.log(`✅  Written: ${filePath}`);

    // 4. Ensure GitHub Pages is enabled
    await ensurePages();

    // 5. Return the live URL
    const liveURL = `https://${GITHUB_USERNAME}.github.io/${REPO_NAME}/portfolios/${slug}`;
    console.log(`🌐  Live at: ${liveURL}`);

    return res.json({ url: liveURL, slug, repo: REPO_NAME });

  } catch (err) {
    console.error('❌  Deploy error:', err.message || err);
    return res.status(500).json({
      error: err.message || 'Deployment failed. Check server logs.',
    });
  }
});

// ─────────────────────────────────────────────────────────────
// START
// ─────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`\n🟢  Folio deploy server running on http://localhost:${PORT}`);
  console.log(`    GitHub user : ${GITHUB_USERNAME}`);
  console.log(`    Repo target : ${GITHUB_USERNAME}/${REPO_NAME}`);
  console.log(`    Pages base  : https://${GITHUB_USERNAME}.github.io/${REPO_NAME}/\n`);
});
